"""Pydantic v2 models for deep research, structured output, and HITL payloads."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


# --- Structured planning output ---


class TaskItem(BaseModel):
    """A single actionable task within a plan."""

    title: str = Field(description="Short imperative title")
    description: str = Field(description="What needs to be done")
    priority: Literal["high", "medium", "low"] = "medium"


class TaskPlan(BaseModel):
    """Structured plan produced by the create_plan tool."""

    goal: str = Field(description="High-level objective")
    tasks: list[TaskItem] = Field(description="Ordered list of tasks")
    summary: str = Field(description="Brief explanation of the plan")


# --- Research data ---


class SearchResult(BaseModel):
    """Single web search result from Tavily."""

    url: str = ""
    title: str = ""
    content: str = ""
    score: float = 0.0


class ResearchFinding(BaseModel):
    """A distilled finding from multiple search results."""

    insight: str = Field(description="Key insight or finding")
    evidence: str = Field(description="Supporting evidence")
    sources: list[str] = Field(default_factory=list, description="Source URLs")


class ResearchReport(BaseModel):
    """Structured research report produced by the synthesize node."""

    title: str = Field(description="Report title")
    summary: str = Field(description="Executive summary")
    key_findings: list[ResearchFinding] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list, description="All source URLs")
    tags: list[str] = Field(default_factory=list)
    methodology: str = Field(default="", description="How the research was conducted")


# --- HITL payloads ---


class HITLOption(BaseModel):
    """A single option presented to the user in an HITL widget."""

    id: str = Field(description="Unique option identifier")
    label: str = Field(description="Display text")
    description: str = Field(default="", description="Optional longer description")
    selected: bool = Field(default=False, description="Whether pre-selected")


class HITLPayload(BaseModel):
    """Typed interrupt payload rendered as a UI widget on the frontend."""

    hitl_type: Literal["checkbox", "yes_no", "select", "text", "review", "confirm"]
    title: str = ""
    message: str = ""
    options: list[HITLOption] = Field(default_factory=list)
    report: ResearchReport | None = None


# --- Explorer instructions ---


class SubTopicList(BaseModel):
    """List of sub-topics suggested by the LLM for research clarification."""

    topics: list[str] = Field(description="Specific sub-topics or angles to investigate")


class ExplorerInstruction(BaseModel):
    """Per-explorer search instruction generated by the orchestrate node."""

    query: str = Field(description="Tavily search query")
    search_focus: str = Field(description="What to focus on in results")
    context: str = Field(default="", description="Additional context for the explorer")


class InstructionList(BaseModel):
    """List of explorer instructions produced by with_structured_output."""

    instructions: list[ExplorerInstruction] = Field(
        description="One instruction per parallel explorer"
    )
